name: mama
description: >
  Starter app

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.2.3+117

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any

  # -- service locator -- #
  provider: ^6.1.2

  # -- state manager -- #
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # -- data -- #
  json_annotation: ^4.9.0
  faker_dart: ^0.2.2

  # -- networking -- #
  dio: ^5.3.3
  pretty_dio_logger: ^1.4.0
  fresh_dio: ^0.4.2
  fresh: ^0.4.3
  retrofit: ^4.4.2

  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.4.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5

  # Persisting
  # drift: ^2.13.1
  # sqlite3: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  # sqlite3_flutter_libs: ^0.5.18

  # Logging
  ispect: ^4.1.2
  stack_trace: ^1.11.0
  ispectify_dio: ^4.0.1
  televerse: ^2.4.4
  # sentry_flutter: ^8.9.0
  # logging: ^1.2.0

  # Utils
  open_filex: ^4.6.0
  flutter_cache_manager: ^3.4.1
  platform_info: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.1.0
  mocktail: ^1.0.1
  reactive_forms: ^17.0.1
  json_serializable: ^6.8.0
  mask_text_input_formatter: ^2.9.0
  icons_launcher: ^2.1.7
  url_launcher: ^6.3.1
  flutter_downloader: ^1.11.8
  scroll_to_index: ^3.0.1
  flutter_local_notifications: ^18.0.1

  # -- audio -- #
  audioplayers: ^6.1.0
  record: ^5.2.0

  # -- media -- #
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  webview_flutter: ^4.10.0
  flutter_pdfview: ^1.3.3

  # -- navigation -- #
  go_router: ^14.2.7

  # -- localization -- #
  flutter_localizations:
    sdk: flutter
  slang: ^4.7.2
  slang_flutter: ^4.7.0

  # -- ui -- #
  flex_color_scheme: ^8.2.0
  tab_container: ^3.5.3
  dotted_border: ^2.1.0
  pin_code_fields: ^8.0.1
  flutter_toggle_button: ^0.0.3
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  reactive_date_time_picker: ^4.0.0
  flutter_envify: ^3.0.1
  action_slider: ^0.7.0
  syncfusion_flutter_charts: ^29.2.7
  calendar_view: ^1.3.0
  delightful_toast: ^1.1.0
  flutter_context_menu: ^0.2.0
  very_good_infinite_list: ^0.9.0
  blur: ^4.0.0

  # -/- text -/-
  auto_size_text: ^3.0.0
  substring_highlight: ^1.0.33
  marquee: ^2.3.0
  google_fonts: ^6.2.1
  flutter_linkify: ^6.0.0

  # -- image -- #
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.1.2
  emoji_picker_flutter: ^3.1.0
  file_picker: ^8.1.2
  flutter_dash: ^1.0.0

  skit:
    git:
      url: https://github.com/nikondrat/skit.git
      ref: future

dev_dependencies:
  # -- testing -- #
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # -- utils -- #
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.5

  # -- codegen -- #
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.0+1
  slang_build_runner: ^4.4.2

  swagger_parser: ^1.22.1
  retrofit_generator: ">=8.0.0 <10.0.0"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/docs/

  fonts:
    - family: icons
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Medium.ttf
        - asset: assets/fonts/SFProText-Bold.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
dependency_overrides:
  skit:
    path: /Users/nikondrat/Documents/work/projects/apps/skit
